language: go
before_install:
    - go get github.com/mattn/goveralls
script:
    - go test -v ./...
    - go test -bench=. ./...
    - roll -stats -sum adler32
    - $HOME/gopath/bin/goveralls -package=./... -service=travis-ci
