language: go
go:
  - "1.x"
  - "1.14"
  - "1.13"
  - "1.12"
  - "1.11"
  - "1.10"
  - "1.9"
  - "1.8"
  - "1.7"
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -v ./...
  - go test -bench=. ./...
  - $HOME/gopath/bin/goveralls -package=./... -service=travis-ci
